name: Build and deploy Node.js app to Azure Web App - PrabhuAttendance

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # ✅ Install & build backend
      - name: Install and build backend
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      # ✅ Install & build frontend (optional, remove if not needed)
      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend # ✅ Only deploy backend folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D94C2A9FA1CA4D338A134959AE36A37F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4E9F873C560C4579BBDCE74366C0CC20 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EC332B9BAF844C6B1C7749537CC4027 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PrabhuAttendance'
          slot-name: 'Production'
          package: .
