name: Build and deploy Node.js app to Azure Web App - AttendanceTracker

on:
  push:
    branches:
      - test2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # ✅ Install & build backend
      - name: Install and build backend
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      # ✅ Install & build frontend (React/Vite/Angular/etc.)
      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build --if-present

      # ✅ Copy frontend build to backend for serving
      - name: Copy frontend build to backend
        run: |
          mkdir -p ./backend/frontend
          cp -r ./frontend/dist ./backend/frontend/

      # ✅ Upload backend with frontend for deployment
      - name: Upload backend for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D424732F2D0840E9A48737BD126C7866 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_203861CBC5B54F6486E6BE2D42B47042 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3FCC108F69D46509BBBAC459F3F51CB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AttendanceTracker'
          slot-name: 'Production'
          package: .
